### PR TITLE
fix(package): installation falls back to XMLRPC

### LINKED ISSUE #170: Package installation fails when REST API is disabled
### What happened?

When trying to install a package with xst (starting with version 1.9.0) on an instance of exist-db that has 

```xml
      <init-param>
         <param-name>hidden</param-name>
         <param-value>true</param-value>
      </init-param>
```

set in `etc/webapp/WEB-INF/web.xml`, effectively disabling the REST API, package installation fails with

```bash
; xst package install spec/fixtures/test-app.xar
Install test-app.xar on https://localhost:8443
Response code 403 (Forbidden)
```

As it fails to fall back to XMLRPC API. As a workaround one can still force XMLRPC use by providing `--rpc` to the installation command.

```bash
; xst package install spec/fixtures/test-app.xar --rpc
```

or by setting it in the configuration (only possible in `.xstrc`):

 ```json
{ "rpc": true }
```

### System Information

```sh
Build: eXist-7.0.0-SNAPSHOT (b032a424e9e92582938080d90b057a14c079df04)
Java: 17.0.6 (Azul Systems, Inc.)
OS: Mac OS X 13.6 (aarch64)
```

### Relevant shell output

```sh
; xst package install spec/fixtures/test-app.xar
Install test-app.xar on https://localhost:8443
Response code 403 (Forbidden)
```

### PR DESCRIPTION
**Pull request by line-o**
fixes #170

Try REST connection, fall back to XMLRPC and inform user that this happened.

```
; xst package install spec/fixtures/test-lib.xar
Falling back to XMLRPC API
Install test-lib.xar on https://localhost:8443
✔︎ uploaded
✔︎ installed
```

### CODE REVIEW

**Comment by line-o** [comment]
I tested this fix locally by setting up an instance that has REST disabled. There is no automated test for this at the moment because do not know how to do this in docker yet. 
@duncdrum help would be appreciated as there will be more REST API used in the future.
@luckydem This is the fix for the issue you reported.

**Comment by duncdrum** [comment]
@line-o I would create another workflow file, not use `services` but modify and assemble the image on the ci server like we do for most stock apps. Basically:

1. pull image
2. copy modified `conf.xml` into image
3. start container (based on modified image)
4. run xst tests

**Comment by line-o** [comment]
@duncdrum Would you be able to share a link to an example?

**Comment by duncdrum** [comment]
https://github.com/eXist-db/eXide/blob/2442c0bf6ebd42782e74a5db945f5c2345428513/.github/workflows/ci.yml#L43-L47 

and 

https://github.com/duncdrum/distroless-exist/blob/01881d6afcedc175e347ee890ecb29372ee4d456/test/bats/02-config-spec.bats#L20-L24

the `run` keyword in the bats test need to be `run:` in gha yml. `docker …` is just the docker command you want to execute

**Comment by line-o** [comment]
How do we maintain modified configurations for each version of exist that is currently in the testmatrix?

**Comment by duncdrum** [comment]
matrix expansion in the yaml file, something like

` docker pull duncdrum/existdb:${{ exist.version }}-j8`

**Comment by line-o** [comment]
@duncdrum shouldn't it be more like

1. pull image
2. start container
3. copy web.xml from container to filesystem
4. modify web.xml (with `sed` for example)
5. copy modified web.xml back into container
6. restart container for modifications to take effect
7. test

**Comment by duncdrum** [comment]
You can do that, it ll take long to run though. As you need a running container for the copy (I think) If you want to do this I would download them from the containers in the unit test phase, and share as artefact or even commit to repo.

Once you commit to repo, you might as well store the changes files and maintain these by hand. Either way works.

**Review by duncdrum — APPROVED** [review]
Nice feature

**Pull request merged**
