### PR TITLE
build: move to conventional commits

### PR DESCRIPTION
**Pull request by line-o**
By default `semantic-release` still uses the angular commit message format.
This PR switches the commit analyser to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
The main advantage is that it allows to signal breaking changes by adding an exclamation mark after the scope.

```
fix!: this is a breaking change 
```

Whereas with angular commit message format one would need to write

```
fix: this is a breaking change

BREAKING CHANGE: Description what is breaking and how to mitigate that.
```

And it happened to me more than once that I forgot to add the colon after `BREAKING CHANGE` and the commit was published as a patch!

### CODE REVIEW

**Comment by line-o** [comment]
(META) @duncdrum I would like to add you as a reviewer but you are not in the list. Can I change that, and if yes how?

**Comment by duncdrum** [comment]
@line-o good idea on conventional commits. If you add this repo to the orgs frontend / node whatever team. I should be able to review. 

This is good to merge

**Review by duncdrum — APPROVED** [review]

**Comment by duncdrum** [comment]
I don’t have write access so I can’t merge, otherwise good to go

**Comment by line-o** [comment]
I am in working on limiting commits in ci. I would like to have that ready as part of this PR.
Turns out I used a wrong scope myself unknowingly (it's docs not doc).
But for this to work now I will need to find the added PRs for both push and pull_request events... again. Last time we ended up splitting the actions per event because the info we get is so different.

**Comment by line-o** [comment]
Ah and the readme needs a contributing section.

**Comment by line-o** [comment]
Now you should be able to merge PRs. But please have a look first.

**Comment by line-o** [comment]
Specifically @duncdrum could you checkout this PR and follow the instructions to get the commit hooks working locally?
That would be great to have validation that it works as intended.

- change a js file by declaring an unused variable
- add the js file and try to commit it
- confirm that it fails to commit because of the unused variable
- remove the offending line and add indentation to an existing line
- commit it it with an invalid message: `[ignore] this is just a test` or so
- confirm that the message is rejected
- commit with a correct message `chore: add variable`
- confirm that the changes were committed but the indentation was corrected

**Comment by line-o** [comment]
In my testing this was the case but I have it setup already.

**Review by duncdrum — APPROVED** [review]
Looking good

**Pull request merged**
